### ISSUE TITLE
Unit tests break on a 32-bit platform

### ISSUE THREAD

**Issue by atifaziz** [SurajGupta/RserveCLI2#35]
All unit tests fail when run on a 32-bit platform at time of launching the server process:

```
RserveCLI2.Test.SexpArrayBoolTest.Various_ArrayBool : System.ComponentModel.Win32Exception : The specified executable is not a valid application for this OS platform.
Stack Trace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RserveCLI2.Test.Rservice..ctor(Boolean showWindow, Int32 maxInputBufferSizeInKb) in C:\RserveCLI2\RserveCLI2.Test\Rservice.cs:line 70
   at RserveCLI2.Test.SexpArrayBoolTest.Various_ArrayBool() in C:\RserveCLI2\RserveCLI2.Test\SexpArrayBoolTest.cs:line 91
```

It seems to be that problem is [hard-coding for x64 only](https://github.com/SurajGupta/RserveCLI2/blob/7eeb0a74762f1dcdfa41d83815bbe24884b190a9/RServeCLI2.Test/Rservice.cs#L48).

**Comment by SurajGupta** [comment]
fixed and build passes.  thanks for the contribution!
